name: recipes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  fluttertoast: ^8.2.8
  flutter_launcher_icons: ^0.14.2
  flutter_image_compress: ^2.0.3  # Use the latest version



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/


